@startuml
left to right direction
skinparam packageStyle rectangle
actor 用户
actor 系统
rectangle Web多轨音频编辑系统 {
  用户 ---- (项目管理)
  ' (项目管理) ..> (打开项目) : include
  ' (项目管理) ..> (保存项目) : include
  (项目管理) ..> (导出项目为音频文件) : include

  用户 ---- (素材管理)
  (素材管理) ..> (导入素材) : include
  (素材管理) ..> (查看素材) : include
  (素材管理) ..> (删除素材) : include

  用户 ---- (轨道管理)
  (轨道管理) ..> (新增轨道) : include
  (轨道管理) ..> (删除轨道) : include
  (轨道管理) ..> (调整轨道顺序) : include
  (轨道管理) ..> (重命名轨道) : include
  (轨道管理) ..> (设置轨道为录制轨道) : include
  (轨道管理) ..> (设置轨道为静音轨道) : include
  (轨道管理) ..> (设置轨道为独奏轨道) : include

  用户 ---- (剪辑管理)
  (剪辑管理) ..> (添加素材片段) : include
  (剪辑管理) ..> (调整素材片段偏移量) : include
  (剪辑管理) ..> (调整素材片段所在轨道) : include
  (剪辑管理) ..> (分割素材片段) : include
  (剪辑管理) ..> (调整素材片段起始点与结束点) : include
  (剪辑管理) ..> (拉伸素材片段) : include

  用户 ---- (编辑器操作)
  (编辑器操作) ..> (纵向横向滚动)
  (编辑器操作) ..> (调整缩放比例)

  用户 ---- (播放控制)
  (播放控制) ..> (开始播放) : include
  (播放控制) ..> (暂停播放) : include
  (播放控制) ..> (停止播放) : include
  (播放控制) ..> (调整进度) : include

  用户 ---- (音频录制)
  (音频录制) ..> (录制音频) : include

  用户 ---- (音效管理)
  (音效管理) ..> (音量调节) : include
  (音效管理) ..> (声道平衡调节) : include
  (音效管理) ..> (效果管理) : include
  (效果管理) ..> (添加音效) : include
  (效果管理) ..> (删除音效) : include
  (效果管理) ..> (编辑音效参数) : include
  (效果管理) ..> (音效参数模板选择) : include

  ' rectangle 音效 {
  '   left to right direction
  '   (音效管理) <... (混响效果管理) : extends
  '   (音效管理) <... (均衡器效果管理) : extends
  '   (音效管理) <... (延迟效果管理) : extends
  '   (音效管理) <... (颤音效果管理) : extends
  '   (音效管理) <... (过滤器效果管理) : extends
  ' }
  ' (音效管理) ..> (混响效果管理) : include
  ' (音效管理) ..> (均衡器效果管理) : include
  ' (音效管理) ..> (过滤器效果管理) : include
  ' (音效管理) ..> (颤音效果管理) : include
  ' (音效管理) ..> (延迟效果管理) : include

  ' (混响效果管理) ..> (添加混响效果) : include
  ' (混响效果管理) ..> (混响模板选择) : include
  ' (混响效果管理) ..> (删除混响音效) : include
  ' (混响效果管理) ..> (编辑效果参数) : include

  ' (均衡器效果管理) ..> (添加混响效果) : include
  ' (均衡器效果管理) ..> (混响模板选择) : include
  ' (均衡器效果管理) ..> (删除混响音效) : include
  ' (均衡器效果管理) ..> (编辑效果参数) : include

  ' (过滤器效果管理) ..> (添加混响效果) : include
  ' (过滤器效果管理) ..> (混响模板选择) : include
  ' (过滤器效果管理) ..> (删除混响音效) : include
  ' (过滤器效果管理) ..> (编辑效果参数) : include

  ' (颤音效果管理) ..> (添加混响效果) : include
  ' (颤音效果管理) ..> (混响模板选择) : include
  ' (颤音效果管理) ..> (删除混响音效) : include
  ' (颤音效果管理) ..> (编辑效果参数) : include

  ' (延迟效果管理) ..> (添加混响效果) : include
  ' (延迟效果管理) ..> (混响模板选择) : include
  ' (延迟效果管理) ..> (删除混响音效) : include
  ' (延迟效果管理) ..> (编辑效果参数) : include

  (音频可视化效果展示) ---- 系统
  (轨道音频素材可视化) <.. (音频可视化效果展示) : include
}
@enduml
