@startuml
actor User

User -> Dropdown: handleContainerClick()
User -> Dropdown: handleEffectMenu();
activate Dropdown
Dropdown -> ContextMenu: createContextMenu();
deactivate Dropdown
User -> ContextMenu: click
ContextMenu -> Dropdown: handler();
activate Dropdown
Dropdown -> AudioEffectAction: addEffect()
deactivate Dropdown
AudioEffectAction -> AudioEffectSaga: addEffectSaga()
AudioEffectSaga -> EventEmitter: emit('EFFECT_ADD_EFFECT');
EventEmitter -> AudioController: addEffect();
@enduml
