@startuml
actor User

User -> FunctionBarAction: click library button
activate FunctionBarAction
FunctionBarAction -> LibraryAction: toggleLibrary()
deactivate FunctionBarAction
LibraryAction -> AudioManage: render

User -> AudioManage: click delete button
activate AudioManage
AudioManage -> LibraryAction: deleteAudio()
activate LibraryAction
LibraryAction -> ChannelSaga: deleteAudiosSliceEffect()
deactivate LibraryAction
deactivate AudioManage
@enduml
