@startuml
actor User

User -> FunctionBarAction: click library button
activate FunctionBarAction
FunctionBarAction -> LibraryAction: toggleLibrary()
deactivate FunctionBarAction
LibraryAction -> AudioManage: render

User -> AudioManage: click delete button
activate AudioManage
AudioManage -> LibraryAction: deleteAudio()
activate LibraryAction
LibraryAction -> ChannelSaga: deleteAudiosSliceEffect()
activate ChannelSaga
ChannelSaga -> ChannelAction: deleteSlice()
ChannelSaga -> EventEmitter: emit('LIBRARY_DELETE_AUDIO')
EventEmitter -> AudioController: deleteAudio()
deactivate ChannelSaga
deactivate LibraryAction
deactivate AudioManage
@enduml
