@startuml
actor User

User -> DropdownItem: handleRemoveEffect()
activate Dropdown
Dropdown -> AudioEffectAction: closeEffectPanel()
AudioEffectAction -> AudioEffectSaga: removeEffectSaga()
AudioEffectSaga -> EventEmitter: emit('EFFECT_DELETE_EFFECT');
EventEmitter -> AudioController: removeEffect();
Dropdown -> AudioEffectAction: removeEffect()
deactivate Dropdown
@enduml
