@startuml
actor User

User -> AudioChannel: showDropdown()
activate AudioChannel
AudioChannel -> Dropdown: render
deactivate AudioChannel
User -> Dropdown: handleRemoveEffect()
activate Dropdown
Dropdown -> AudioEffectAction: removeEffect()
deactivate Dropdown
@enduml
