@startuml
actor User

User -> MenuItem: Click
activate MenuItem
User -> Editor: audioFileDropHandler ()
activate Editor
MenuItem -> MenuItem: clickHandler
activate EventEmitter
MenuItem -> EventEmitter: emit('MENU_IMPORT')
deactivate MenuItem
EventEmitter -> AudioController: selectFile()
deactivate EventEmitter
activate AudioController
AudioController -> LibraryAction: addAudio()
Editor -> AudioController: handleFile()
deactivate Editor
@enduml