@startuml
actor User

User -> DropdownItem: handleOpenEffectPanel()
activate DropdownItem
DropdownItem -> AudioEffectAction: openEffectPanel()
deactivate DropdownItem

User -> EffectPanel: handlePresentChange()
activate EffectPanel
EffectPanel -> AudioEffectAction: modifyEffect()
AudioEffectAction -> AudioEffectSaga: updateEffectSaga()
AudioEffectSaga -> EventEmitter: emit('EFFECT_UPDATE_EFFECT');
EventEmitter -> AudioController: updateEffect();
deactivate EffectPanel
@enduml