@startuml
actor User

User -> ControlBar: click play button
activate ControlBar
ControlBar -> ControlBar: handlePlayClick()
ControlBar -> FunctionBarAction: requestPlay()
ControlBar -> EventEmitter: emit('requestPlay')
activate EventEmitter
EventEmitter -> AudioController: play()
ControlBar -> ControlBar: playRafEffect()
ControlBar -> EventEmitter: emit('editorIndicatorChanged')
deactivate ControlBar
EventEmitter -> Editor: editorIndicatorChangedEffect()
activate Editor
Editor -> Editor: rerenderIndicator(false)
deactivate Editor
deactivate EventEmitter

@enduml
