@startuml
actor User

User -> ControlBar: click play button
activate ControlBar
ControlBar -> ControlBar: handlePlayClick()
ControlBar -> FunctionBarAction: requestPlay()
ControlBar -> EventEmitter: emit('requestPlay')
activate EventEmitter
EventEmitter -> AudioController: play()
deactivate ControlBar
EventEmitter -> Editor: playingEffect()
activate Editor
Editor -> Editor: rerenderIndicator(false)
activate Editor
Editor -> ControlBar: indicatorChangeEffect
note left: update time string
Editor -> Editor: updateScrollX
deactivate Editor
deactivate Editor
deactivate EventEmitter

@enduml
