@startuml
actor User

participant AudioBlock order 20
participant AudioController order 30

User -> AudioBlock: user drop a audio slice
activate AudioBlock
AudioBlock -> AudioBlock: graphEffect()
group Refresh Graph Process
activate AudioBlock
AudioBlock -> VisualEffect: getCanvas()
VisualEffect --> AudioBlock: graphBase64
deactivate AudioBlock
end

deactivate AudioBlock
User -> EditorAction: updateZoom()
activate EditorAction
AudioBlock -> AudioBlock: graphEffect()
deactivate EditorAction

User -> AudioBlock: stretch slice
activate AudioBlock
AudioBlock -> AudioBlock: graphEffect()
deactivate AudioBlock

@enduml
